"""create job skill requirements

Revision ID: 48884966ac50
Revises: 661f8e77b9e4
Create Date: 2026-08-25 16:42:30.619092

Prompt 4.2. Job-side skill requirements derived deterministically from a
saved job description.

Three choices here are load-bearing rather than incidental:

  * `saved_job_id` CASCADES. A requirement is derived data with no life
    of its own — deleting the job must delete it. That cascade is also
    how OWNERSHIP works: there is no user_id column, because the only
    route to these rows is through a saved job whose owner is already
    checked.
  * `skill_id` uses RESTRICT, matching candidate_skills. Canonical
    skills are shared vocabulary; deleting one out from under the rows
    that reference it should fail loudly.
  * UNIQUE(saved_job_id, skill_id) is the reconciliation key. Extraction
    upserts on it, so re-running over an unchanged description writes
    nothing and a re-classified skill updates in place rather than
    accumulating a second row.

`requirement_level` is plain VARCHAR with NO database CHECK, matching
resumes.status and candidate_skills.status — the vocabulary is validated
at the application boundary so adding a level later is a code change,
not an ALTER TYPE. `confidence` DOES get a CHECK, because a numeric
range is a permanent invariant rather than a vocabulary.

Schema only: no rows. Nothing here creates candidate skills or skill
evidence — that boundary belongs to the candidate side and is asserted
by tests.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48884966ac50"
down_revision: str | Sequence[str] | None = "661f8e77b9e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_skill_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("saved_job_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_level", sa.String(length=20), nullable=False),
        sa.Column("matched_term", sa.String(length=80), nullable=False),
        sa.Column("excerpt", sa.String(length=500), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("extraction_method", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_job_skill_requirements_confidence_range"
        ),
        sa.ForeignKeyConstraint(["saved_job_id"], ["saved_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("saved_job_id", "skill_id", name="uq_job_skill_requirements_job_skill"),
    )
    op.create_index(
        op.f("ix_job_skill_requirements_saved_job_id"),
        "job_skill_requirements",
        ["saved_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_skill_requirements_skill_id"),
        "job_skill_requirements",
        ["skill_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_skill_requirements_skill_id"), table_name="job_skill_requirements")
    op.drop_index(
        op.f("ix_job_skill_requirements_saved_job_id"), table_name="job_skill_requirements"
    )
    op.drop_table("job_skill_requirements")
    # ### end Alembic commands ###
