"""create saved jobs table

Revision ID: 661f8e77b9e4
Revises: 04b169c2f73e
Create Date: 2026-08-25 12:33:46.268916

Prompt 4.1. User-owned saved job descriptions.

Two choices here are deliberate rather than incidental:

  * `employment_type` is plain VARCHAR with NO database CHECK, matching
    `resumes.status` and `profiles.experience_level`. The vocabulary is
    validated at the application boundary
    (app.schemas.saved_job.EmploymentType) precisely so adding a value
    later is a code change, not an ALTER TYPE migration.
  * `description` is TEXT, not VARCHAR(n). A posting has no useful
    column-level length, so the 60,000-character ceiling is enforced in
    the schema where it produces a readable error rather than a driver
    exception — the same split as the resume upload size limit.

Schema only: no rows, and nothing is fetched from any `source_url`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "661f8e77b9e4"
down_revision: str | Sequence[str] | None = "04b169c2f73e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("employment_type", sa.String(length=30), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_jobs_user_id"), "saved_jobs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_jobs_user_id"), table_name="saved_jobs")
    op.drop_table("saved_jobs")
    # ### end Alembic commands ###
